version: '3'
services:
    nginx:
        image: 'nginx:latest'
        restart:
            always
        ports:
          - 80:80
          - 443:443
        volumes:
            - ./conf/:/etc/nginx/conf.d/
        environment:
          - NGINX_PORT=80
          - TZ=Asia/Shanghai
        networks:
            - sail
networks:
    sail:
        driver: bridge
